version: '3'
services:
  app:
    build: .
    container_name: worldapp-app-1  # Set a fixed name for the app container
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    build: db/.
    container_name: worldapp-db-1  # Set a fixed name for the DB container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: world
