version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"  # Expose your app's port, if needed
    environment:
      - DB_HOST=db  # The app will refer to the database as 'db'

  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"  # Expose MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: example  # Set MySQL root password
      MYSQL_DATABASE: world  # Database name



