name: CI Pipeline with Logs

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose and build the services
      - name: Build and Start Services
        run: docker-compose up --build -d

      # Step 3: Wait for the database to be ready
      - name: Wait for Database to Be Ready
        run: |
          apt-get update && apt-get install -y netcat
          until nc -z db 3306; do
            echo "Waiting for database...";
            sleep 3;
          done
          echo "Database is ready!"

      # Step 4: Run tests inside the app container
      - name: Run Tests
        run: docker exec worldapp-app ./mvnw test

      # Step 5: Capture logs (if the test step fails)
      - name: Capture Logs on Failure
        if: failure()  # Only run if a previous step fails
        run: |
          echo "Capturing logs from Docker containers..."
          docker-compose logs app
          docker-compose logs db

      # Step 6: Stop and cleanup services
      - name: Stop and Cleanup
        run: docker-compose down
