name: Multi-Job Workflow for World and Hello World Apps
on: push

jobs:
  build_and_test:
    name: Build and Test Application with Database
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Step 2: Set up Java Development Kit (JDK) 23
      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'adopt'

      # Step 3: Set JAVA_HOME environment variable
      - name: Set JAVA_HOME environment variable
        run: echo "JAVA_HOME=$(dirname $(dirname $(which java)))" >> $GITHUB_ENV

      # Step 4: Check Java version
      - name: Check Java version
        run: java -version

      # Step 5: Compile and package the application with Maven
      - name: Build Application with Maven
        run: mvn package

      # Step 6: Build and run the application and database with Docker Compose
      - name: Run Docker Compose
        run: docker compose up --build --abort-on-container-exit

      # Step 7: View container logs after the build and test
      - name: View Logs
        run:
          docker logs worldapp-app-1
