name: World Sorting App 
on: push

jobs:
  build:
    name: Sorting App Action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile and Package with Maven
        run: mvn package

      - name: Build Docker Image
        run: docker build -t semimage .
