name: Multi-Job Workflow for World and Hello World Apps
on: push

jobs:
  build_and_test:
    name: Build and Test Application with Database
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Step 2: Set up Java Development Kit (JDK) 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Compile and package the application with Maven
      - name: Build Application with Maven
        run: mvn package

      # Step 4: Build and run the application and database with Docker Compose
      - name: Run Docker Compose
        run: docker compose up --build --abort-on-container-exit

        # Step 5: View container logs after the build and test
      - name: View Logs
        run: |
          echo "==== Application Logs ===="
          docker logs $(docker ps -q -f name=app | head -n 1)
          echo "==== Database Logs ===="
          docker logs $(docker ps -q -f name=db | head -n 1)