
name: Multi-Job Workflow for World and Hello World Apps
on: push

jobs:
  build_and_test:
    name: Build, Test, and Run Application with Database
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Step 2: Set up Java Development Kit (JDK) 15
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      # Step 3: Compile and package the application with Maven
      - name: Build Application with Maven
        run: mvn package

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: mvn test

      # Step 5: Run Integration Tests
      - name: Run Integration Tests
        run: mvn verify

      # Step 6: Build and run the application and database with Docker Compose
      - name: Run Docker Compose
        run: docker compose up --build --abort-on-container-exit